name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Smoke tests
        run: |
          python scripts/iris.py --help
          python scripts/imbalance.py --help
          python scripts/forest_vs_logit.py --help
          python scripts/importance_demo.py --help
          python scripts/gridsearch_mixed.py --help

